### ISSUE TITLE
Migrate Language Communities from v3

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#101]
During v3 -> v4 migration it has been decided that we want to:

* Create a v4 community for each v3 language community (maintain title)
* Create a new, open protocol for that new v4 community
* During migration of dictionary words and word lists, in the case where the entity has no protocols, assign the newly created v4 protocol. Potentially, for entities with existing protocols, we might want to add the new protocol as well.
* Migrate group memberships from the language community. We need to think about this more, but I think language contributor and language steward map directly from language community to protocol (those roles are in protocols in v4). Then maybe language community "administrator member" maps to "community manager" of the newly created v4 community?

**Comment by michael-wynne-wsu** [comment]
"language community "administrator member" maps to "community manager" of the newly created v4 community?"

I think yes, AND protocol steward of the open protocol.
