### ISSUE TITLE
Dictionary word location

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#108]
Need to add the "full" geocode location field like DH as well.

**Comment by nick-deer** [comment]
@michael-wynne-wsu it's added!

**Comment by michael-wynne-wsu** [comment]
@nick-deer Looks good! Sorry one more thing, can you add the location description field too? In my head I group the taxonomy, geojson, and description field as a location "bundle"

**Comment by nick-deer** [comment]
It's added!
