### ISSUE TITLE
Content Labels

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#109]
More question than issue. All content types default to "title" as their title/name field. Can that be renamed per-content type?

**Comment by steve-taylor-wsu** [comment]
The label can, yes. It exists in user-space, we'd only be setting the default. For example: /admin/structure/types/manage/word_list

The actual field machine name is set by the entity type definition (e.g., all nodes have a 'title').

**Comment by michael-wynne-wsu** [comment]
Great, I'll submit some issues to update our labels then.

**Comment by michael-wynne-wsu** [comment]
Trying to avoid generic "title" labels for content and structure.

- Community: Community name
- Cultural protocol: Cultural protocol name
- Category: Category name
- Collection: Collection name
- Word list: Word list name
- Personal collection: Personal collection name
- Person record: Name
- Digital heritage item: Title
- Dictionary word: Term (TBD on this one...)

**Comment by nick-deer** [comment]
@michael-wynne-wsu Alright I changed all the content labels except for dictionary word (since it was marked as TBD)

**Comment by michael-wynne-wsu** [comment]
@nick-deer thank you!

I'm trying too hard to be clever, let's stick with "Term" for dictionary word (as it is in v3).

**Comment by nick-deer** [comment]
Okay I made the change, should be the last of them!
