### ISSUE TITLE
Some migrations still allowing for null protocols

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#111]
At the very least, media can be erroneously saved with no protocols, which is throwing `InvalidArgumentException` in CulturalProtocolItem. We should definitely address the migration and maybe be less aggressive throwing the exception.

**Comment by michael-wynne-wsu** [comment]
Flagging person records in here. Don't recall if it's null protocols or another setting, but something protocol related is preventing migration.

**Comment by steve-taylor-wsu** [comment]
I missed capturing part of the protocol field addition for the person type on v3. I've corrected that and pushed up the changes so the most recent v3 develop branch should be fixed for that particular issue.

**Comment by michael-wynne-wsu** [comment]
Got it. We're going to run another test migration tomorrow morning.

**Comment by steve-taylor-wsu** [comment]
Nice, that's great. Make sure both v3 and v4 are fresh, I've made changes to both this afternoon. I believe this issue is mostly addressed now. 

If anything with missing/invalid protocols makes its way into the database, we're setting the protocols to empty, which in v4 is UID 1/owner only. Before we were doing the "right" thing but that crashes the site in a lot of other Drupal code.

Also, right now we're expecting the migration to be run as UID 1 on the v4 side. Otherwise, protocol enforcement could cause some problems unless the user running the migration has full access to all protocols.
