### ISSUE TITLE
Related content teasers

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#121]
Related content teasers in both sidebar and bottom should be carried over.

Allow enabling/disabling those individually.
https://plateauportal.libraries.wsu.edu/digital-heritage/bakery-chemawa-school
https://mukurtu.org/support/toggling-related-items-teasers/

**Comment by michael-wynne-wsu** [comment]
I think a more space-efficient design for the bottom teaser would be a good upgrade. Maybe like a 3-column pagination.

Sidebar should not be limited to related DH only - any related content should display.

**Comment by michael-wynne-wsu** [comment]
Bottom can likely use teaser or other existing view mode
Sidebar will need a new view mode.

**Comment by michael-wynne-wsu** [comment]
The toggles also need to be built, not just the display.

**Comment by michael-wynne-wsu** [comment]
Both toggles are global across all content types - not per-type.

**Comment by michael-wynne-wsu** [comment]
Thanks @nick-deer 
Just to confirm:

1. What is "Related Content Display: Display value of the item's related content field as is. /  Display value of the item's related content field, but also include content that includes this item as related content." supposed to do?
2. Toggling "Related Content Teasers Display" doesn't currently do anything - I'm guessing that's theming work, yes?
3. I was expecting TWO toggles - one for each teaser location.
4. Don't worry about pagination.

![Screenshot 2024-02-22 at 1 59 56 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/46b52050-6297-4449-af1d-bca1be67130f)

![Screenshot 2024-02-22 at 2 00 29 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/7025f6d7-a6a6-4a36-90eb-790add441dd4)

**Comment by nick-deer** [comment]
Hi @michael-wynne-wsu,

1. This is a little confusing, so let me illustrate with an example. Here I have a DH item with one related content item, a person named Jean Valjean:
![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/43937352/ececa8a7-22ed-4f9d-8fb7-c481f49e8442)

If the "Display value of the item's related content field, but also include content that includes this item as related content" option is selected in settings, when I click on Jean Valjean, the Related Content field references the DH item that references Jean Valjean as related content (in addition to whatever related items were selected in the form):

![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/43937352/b2b59fd5-5d12-4dd4-a8b1-40089ac0dfd6)

I suppose it's just a way to have the referrer and the referred content items reference each other. When I select the "Display value of the item's related content field as is" option, that DH item disappears from the related content field and only the related content that was set in the form is displayed:

![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/43937352/c8942db6-e990-4dbd-9861-1cf2fd7630c5)

Let me know if that answers your question!

2. Yes, that's right. The config variables are set for a themer to hopefully take over
3. Oops sorry, I can add that real quick!
4. Great thanks!

**Comment by nick-deer** [comment]
@michael-wynne-wsu just added the separate toggles!

**Comment by michael-wynne-wsu** [comment]
@nick-deer 
1) Gotcha - now that I read it with that context it makes sense. We'll want to change the wording on that, but yes I see it working. One note, that only seems to be affecting the lower teaser, the sidebar never displays the reciprocal one - but if that's not something quick, I think you can move on (and you might have updated this already with the second toggle addition).

2) Great.

3) I'll check this tomorrow.

Unless there's more cleanup on this, I think we can move it into the "functional" category and you can move on to the next item!

**Comment by michael-wynne-wsu** [comment]
@nick-deer FYI this issue has gotten too messy and is mostly complete. Starting a new one for specific items here: https://github.com/MukurtuCMS/Mukurtu-CMS/issues/334
