### ISSUE TITLE
Migrate - UID 1

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#141]
When Brian, Alex and I were doing some testing, we realized that UID 1 username and password in the V4 site were changed to the V3 information.

Not explicitly an issue, may just merit a warning/clear documentation?

**Comment by steve-taylor-wsu** [comment]
Ah good catch, this is a byproduct, not intentional. I think we'll try and exclude UID 1 from migration and if that's not an easy option then we'll document for now.

**Comment by michael-wynne-wsu** [comment]
Only thought there is that in MANY sites, UID 1 will also be the main community manager and protocol steward.

**Comment by steve-taylor-wsu** [comment]
Sorry I misspoke. Exclude from the user migration step, e.g., name, password. Memberships are all handled outside of user migration. Maybe migrating the password is desirable though? Would you rather have a note, warning them that their password might be changed during migration? Go all in on consistency with their v3 site?

**Comment by michael-wynne-wsu** [comment]
No, let's exclude that. They may have created new UID 1 info on the new site intentionally.

And if we can avoid them running into the same surprise I did, that would be good (login with v4 UID 1, migrate, don't notice credentials change, log out, panic)

**Comment by steve-taylor-wsu** [comment]
@nick-deer could you please take a look and see if there's a good way to exclude UID 1 from `mukurtu_cms_v3_users`?

**Comment by steve-taylor-wsu** [comment]
UID 1 has been moved to a separate migration that does not modify the name/display name/email/password. We still need to "migrate" UID 1 so that our membership migrations work as intended for UID 1. I tested this with the PPWP migration, and it looks good to me.
