### ISSUE TITLE
Incorrect default value for field_knowledge_keepers on Digital Heritage

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#146]
The empty string, `->setDefaultValue('')`, is not a valid default value for an entity_reference_revisions field. The empty string is an opinionated value (not empty, despite what PHP thinks!). Here we'd be better either omitting setDefaultValue or setting NULL. The goal is to have no value for this field when a user saves a DH item with no paragraphs in this field.

**Comment by nick-deer** [comment]
I took out the `setDefaultValue()` setting.
