### ISSUE TITLE
Can you pick a specific UUID for new content on import?

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#152]
* Can you?
* Should you be able to?
* Document this somewhere

**Comment by michael-wynne-wsu** [comment]
Context note: this mostly comes from my experience with v3 where
1) It was required (If it's not, great!)
2) It is used to connect media, related content, MPDs, etc within a complex import.

**Comment by steve-taylor-wsu** [comment]
@michael-wynne-wsu @nick-deer 

Confirming that yes, you can specify a UUID to create fresh content in Drupal using the Mukurtu CMS importer. Works well actually, seems useful for when you're importing fresh content but might need to tweak with repeated runs, because you can use UUID for both insert and update.

**Comment by michael-wynne-wsu** [comment]
Excellent, very glad that it's a useful option! And very glad it's not required for basic imports.
