### ISSUE TITLE
Media entity name/alt text auto-population

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#155]
For cases where we haven't already defined specific behavior, we want to automatically populate any blank name and alt text fields for media assets that support them, based on the filename of the file/image entity.

We should be able to adapt/generalize the current document media entity handling which does some of this already.

**Comment by nick-deer** [comment]
@michael-wynne-wsu I added the changes and they're ready for review!
