### ISSUE TITLE
Cultural Protocol Formatter not showing protocols on DH full view

### ISSUE THREAD

**Issue by nick-deer** [MukurtuCMS/Mukurtu-CMS#170]
![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/43937352/596b402f-713a-4753-904a-6c352db1714f)
![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/43937352/a7d9cba0-0d83-4d23-b4bc-8d05d6966d75)

**Comment by steve-taylor-wsu** [comment]
For context, it looks like I never fully finished `CulturalProtocolFormatter`.

Depending on what kind of formatter is wanted, you might be able to mirror or use something from Entity Reference. For example, if linked labels are what is wanted, `EntityReferenceLabelFormatter` could be used as reference or it might not be too bad to coerce what you have (CulturalProtocolItem?) into what that formatter wants (EntityReferenceItem?).

Alternatively skip all that and simply output markup... Especially for this method, watch out for the inaccessible reference issue (https://github.com/WSU-CDSC/mukurtu-cms/discussions/35)

**Comment by nick-deer** [comment]
@michael-wynne-wsu Protocols are displaying on DH full view now! Access seems to work as intended--the only protocols that show up for the user are the ones they have privilege to view. Let me know if it works for you as well!

**Comment by michael-wynne-wsu** [comment]
Yep seems good to me, thanks!
