### ISSUE TITLE
Facets in any map browse page are not working

### ISSUE THREAD

**Issue by taylor-steve** [MukurtuCMS/Mukurtu-CMS#171]
Getting a 404 on `/facets-block-ajax`

**Comment by pjudge** [comment]
The facets appear to be working on map browse page, however they become disabled after they're enabled, and there is no 'clear' or 'reset' button.

**Comment by michael-wynne-wsu** [comment]
@pjudge good catch on those. I don't recall that behaviour earlier but could have missed it. Agree that a clear/reset button on all browse pages is needed (it was in v3 - not sure if Morgan just didn't get to it or had a reason to omit it)

**Comment by pjudge** [comment]
Handoff note: I think this ticket could be closed after my latest PR is merged https://github.com/MukurtuCMS/Mukurtu-CMS/pull/340

**Comment by michael-wynne-wsu** [comment]
Moving all of this into https://github.com/MukurtuCMS/Mukurtu-CMS/issues/351
