### ISSUE TITLE
Add creating external embed media to in-content modal

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#181]
Current only accessible via the dashboard, add it to the other on the fly media creation

**Comment by nick-deer** [comment]
@michael-wynne-wsu Finished a first pass on it!

**Comment by michael-wynne-wsu** [comment]
@nick-deer worked as expected with a TimelineJS (iframe) embed.

Display is obviously another matter, but I think this specific issue is complete.

<img width="1440" alt="Screenshot 2023-12-08 at 1 36 41 PM" src="https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/5ec5ca44-9732-4ff0-8ad2-783687771134">
