### ISSUE TITLE
Original Date YYYY input validation/change

### ISSUE THREAD

**Issue by alexmerrill** [MukurtuCMS/Mukurtu-CMS#184]
I mistyped my way into a five digit year input (YYYYY)-- didn't notice until I hit save and got an error screen.  Would rather have the input field validate/error check during input and not on save of the node, if possible -- Does that make sense?

**Comment by nick-deer** [comment]
@alexmerrill Thanks for catching this error! I pushed a change up--five digit years don't crash the site anymore. The maximum year you can put in is 32767, and should you go over it, the widget will catch it without crashing. Let me know if you find any more issues!
