### ISSUE TITLE
Category thumbnail field

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#201]
Category taxonomy does not include thumbnail field, this needs to be added.

**Comment by pjudge** [comment]
@michael-wynne-wsu Where does this appear?

**Comment by nick-deer** [comment]
@michael-wynne-wsu It's added! Unless you've got feedback for it I think this issue is good to close

**Comment by michael-wynne-wsu** [comment]
@nick-deer tested and confirmed. I'm happy with that, please do close this!
