### ISSUE TITLE
Search settings changing when switching between browse views

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#208]
Morgan noted that search terms/facet selection was sticky when swapping between map and list/grid views, wasn't sure how to change it.

I think that is actually preferred behaviour - being able to change browse views without search resetting sounds like an expected experience..

**Comment by michael-wynne-wsu** [comment]
@pjudge just flagging this as an FYI form when Morgan was working on it. Unless you think it needs further discussion we can close this.

**Comment by pjudge** [comment]
@michael-wynne-wsu I agree -- the preferred behavior should be sticky. But I'm not even seeing the stickiness happen now so I'm working on debugging this.

**Comment by michael-wynne-wsu** [comment]
Interesting, something definitely changed in the interim then. Thanks!

**Comment by michael-wynne-wsu** [comment]
It seems like this is related to the ?active=list/grid/map in the URL.

I have vague memory of Morgan mentioning the need for a different map page that was basically integrated with that view switcher. @nick-deer any chance you know more about this?

![Screenshot 2024-05-17 at 10 38 33 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/e464ddd8-bdad-41f7-80d8-cd1c2011a2ba)

**Comment by michael-wynne-wsu** [comment]
V3 grid/list just changes a class on the content. 

V4 links to more complex parameters/page refresh

**Comment by pjudge** [comment]
Handoff note: I **believe** this is working as expected with my latest PR https://github.com/MukurtuCMS/Mukurtu-CMS/pull/340

**Comment by michael-wynne-wsu** [comment]
@nick-deer settings are sticky, but I'm getting some odd behaviours, like results from multiple views showing on the page when switching views.

![Screenshot 2024-06-03 at 9 46 11 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/3e60c8f3-e77b-4c51-8b93-0d7493250420)
