### ISSUE TITLE
Determine theming needed for admin pages

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#209]
Can likely use bartik or other stock theme for most admin pages. But TBC

**Comment by michael-wynne-wsu** [comment]
@alexmerrill I believe Claro is the new default admin theme in D9/10, so we may want to see if that's a preferred admin theme to Bartik.

**Comment by michael-wynne-wsu** [comment]
Admin pages will use admin theme, not Mukurtu theme.  

This includes node create pages, etc. 

Some pages may need to be adjusted though.

**Comment by pjudge** [comment]
Just adding a note here: Claro is configured as the default admin theme, and edit screens are also set to use Claro. There is another ticket for someone to look at ensuring custom modules add/edit screens use Claro as well (this came up in discovering Digital heritage node functionality).

**Comment by michael-wynne-wsu** [comment]
@pjudge was this included in the big PR yesterday or is it a new change since then? I just ran a fresh install and Claro still wasn't enabled/set by default.

**Comment by pjudge** [comment]
@michael-wynne-wsu This config looks like it was merged 4 days ago: https://github.com/MukurtuCMS/Mukurtu-CMS/blob/main/config/install/system.theme.yml. I'm not sure why it wouldn't have been imported, I can look into it!

**Comment by pjudge** [comment]
@michael-wynne-wsu There's some php in the install file setting the default themes, that's overriding the config. 😄 I can update that for my next PR
