### ISSUE TITLE
Location data not migrating

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#211]
Location data isn't migrating from v3 > v4

**Comment by michael-wynne-wsu** [comment]
@nick-deer This would be a relatively high priority item to look at.

**Comment by nick-deer** [comment]
@michael-wynne-wsu I finished a pass on this, location data seems to be migrating!

**Comment by michael-wynne-wsu** [comment]
@nick-deer just tested on a clean install and yes, it's working, I think you can close this.
