### ISSUE TITLE
Person record date fields - should support partial dates

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#220]
Date born and date died should support partial dates (same as DH item original date field). Currently they only accept complete YYYY-MM-DD values

/node/add/person

**Comment by nick-deer** [comment]
@michael-wynne-wsu partial dates now supported on Person entities!

**Comment by michael-wynne-wsu** [comment]
@nick-deer looks good to me. Can you please change the date display on person records to be the same as is it on DH items?

**Comment by nick-deer** [comment]
@michael-wynne-wsu I finally got it! There was one config file I missed haha. Confirmed the change on Gitpod, let me know if you see it too

**Comment by michael-wynne-wsu** [comment]
@nick-deer confirmed! Closing as completed, thank you!
