### ISSUE TITLE
Dictionary browse page

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#239]
Broadly copy v3 eg: https://plateauportal.libraries.wsu.edu/dictionary

Search/facet controls:
- Sort (term/translation)
- Language 
- Word lists
- Part of speech
- Keywords
- Community/protocol?
- Search

Glossary list - filter by first "letter".

Search previews should display term, translation, recording. 
NOTE: in v3 the term field is overridden by alternate spelling and that is weird.

**Comment by michael-wynne-wsu** [comment]
Add content type filter to expose words and wordlists.

**Comment by michael-wynne-wsu** [comment]
Thumbnails need to be displayed in teaser/search results.

**Comment by michael-wynne-wsu** [comment]
at /dictionary

**Comment by nick-deer** [comment]
@michael-wynne-wsu should I configure this for solr as well?

**Comment by michael-wynne-wsu** [comment]
@nick-deer Short answer yes. All our default search pages should be configured for search API and Solr if possible.

**Comment by nick-deer** [comment]
Alright @michael-wynne-wsu I finished a first pass on the dictionary browse page! When you get the chance, let me know what you think. I am still configuring the solr version of it, so I'll tell you when that's ready for testing as well.

**Comment by michael-wynne-wsu** [comment]
@nick-deer almost there!

1) Add word lists as a facet if possible (similar to how collection is a facet on DH browse)
2) This is relevant for all browse pages - in the past we've only exposed community as a facet, can we do protocol as well?

And something new... let me know if this needs a separate issue, but adding a map browse view as well.

**Comment by nick-deer** [comment]
Can do! About map browse, do you mean you want another page for it, like in its own tab next to Browse, Browse DH, Browse Dictionary? Or do you want it to be on the Dictionary Browse page? I definitely remember seeing map browse stubbed out in code, I'm not sure why it's not there anymore but we probably all talked about it at some point...

**Comment by michael-wynne-wsu** [comment]
@nick-deer 

On the dictionary browse page. Probably the same concept as the DH browse page where you switch between list and map view.

**Comment by nick-deer** [comment]
alright @michael-wynne-wsu I figured out the config issues and pushed up some config for dictionary browse solr! I also added cultural protocols as a facet to both solr and normal dictionary browse.

**Comment by michael-wynne-wsu** [comment]
Excellent, thanks @nick-deer !
Overall working well, couple thoughts:

1) Map browse was not included yet, right? (if it was, I'm not seeing it)
2) Add the recording field to summary/preview (in v3 it's the summary display mode on this page). Needs to include the actual recording/media asset and the media contributor field.

**Comment by nick-deer** [comment]
@michael-wynne-wsu added the contributor field and changed the recording field to show the media asset! And yes, the map browse is still in progress.

**Comment by michael-wynne-wsu** [comment]
@nick-deer awesome - I trust that it's there, just not displaying as expected since the pages/views haven't been themed yet (screenshots for reference just in case it's looking different for you).

Additionally, we want that contributor field to display with all audio files within dictionary words - so on the dictionary entry page, sample sentence and recording field, etc... Not sure if we want to extend it to other content types yet...

![Screenshot 2024-04-24 at 8 40 00 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/9d6ccc1e-e2ba-4b2f-a5ef-06831ee68642)

![Screenshot 2024-04-24 at 8 40 08 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/5202e62a-2d22-4cf1-9661-470267d692a1)

![Screenshot 2024-04-24 at 8 39 12 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/f1b02f1e-e619-49b7-9bb3-1ceb97979aea)
![Screenshot 2024-04-24 at 8 39 19 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/ffff6fe6-91d3-444d-926b-5573744518e9)

**Comment by nick-deer** [comment]
@michael-wynne-wsu I was unable to replicate the recording field display issue you mentioned. I tried it on my local dev instance and a Gitpod instance, with Bartik and the custom theme. Are you getting any errors or warnings in the log?

**Comment by michael-wynne-wsu** [comment]
@nick-deer I'm getting the exact same behaviour both with ddev and gitpod (new installs within the last half hour).

Both show the same logs, nothing seemingly relevant.

Have tested with multiple audio files...

![Screenshot 2024-04-25 at 1 31 01 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/9ad63ea9-cc1e-43fa-9372-99b2779cce83)

BUT, that was all in Chrome! I'm seeing different behaviour in Firefox - still no audio contributor field, but FF's native audio player IS displaying.

<img width="1412" alt="Screenshot 2024-04-25 at 1 33 23 PM" src="https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/e47cff82-9e48-49dc-8aaa-db42b195f2ba">

**Comment by nick-deer** [comment]
Oh, I didn't consider that different browsers could be the explanation! I develop in Firefox so that's why I didn't notice. I'll look into this next week!

**Comment by michael-wynne-wsu** [comment]
@nick-deer we will also want to test everything in Safari at some point. I'm primarily on Chrome for work stuff, but also use FF for my own use.

**Comment by nick-deer** [comment]
@michael-wynne-wsu I found the specific bug causing the recording field to look weird, it's been logged: https://www.drupal.org/project/blazy/issues/3424712. It's a recent issue as of Feb 2024 so maybe there's a chance they'll release a patch!

**Comment by michael-wynne-wsu** [comment]
@nick-deer that's great to know - I'll log a separate issue so we remember to check on it.

I'm still not seeing the audio contributor field displaying though, not sure if that's a separate issue or related.

**Comment by pjudge** [comment]
@michael-wynne-wsu When you mention the thumbnail for dictionary words, do you have an example of what that should look like in the teaser display?

**Comment by pjudge** [comment]
@michael-wynne-wsu Additionally, is there a field complete dictionary term node on the ppwp3 site that I have a login to? I tried creating one for myself but kept getting errors regarding permissions.

**Comment by michael-wynne-wsu** [comment]
@pjudge Just getting to these after the long weekend, we can discuss this morning but before then...

1) Thumbnail - no, that's a new field in v4 so I don't have an example. Ideas, yes.
2) Field complete example - I'm creating one (but that site is grindingly slow), will link when done.

**Comment by michael-wynne-wsu** [comment]
- [ ] Change to only list dictionary word content type (remove word lists)
- [ ] Replace the content type dropdown with a word list dropdown for filtering
- [ ] Fields to include in teaser: thumbnail, term, translation (any from first word entry paragraph), recording + recording contributor (any from first word entry paragraph)

**Comment by pjudge** [comment]
I'm not able to fully test all the facets at this time! However, I do think the styles included here will account for them.

**Comment by michael-wynne-wsu** [comment]
@nick-deer on gitpod I'm still seeing the "old" facets. Do you think this is something worth trying to debug as is, or should we consider merging the PR just to get everything on the same branch?

**Comment by nick-deer** [comment]
@michael-wynne-wsu I think we should hold off on merging until I can get a look at the files and compare if they're different at all to main. I have a feeling that some config files aren't updating. If I can't find anything, I'm in favor of merging and debugging from there, I'll let you know!

**Comment by michael-wynne-wsu** [comment]
The styled facets ARE showing correct after the PR merge for me in GitHub. I'm going to close this ticket and open a new one for remaining browse page notes.
