### ISSUE TITLE
Personal collections fields and display

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#243]
Add summary field so that it can be included in migrations.

Personal collections don't support sub-collections. That's fine, just a noted difference between them and regular collections.

Otherwise the display can be a copy of the regular collection display.

**Comment by nick-deer** [comment]
@michael-wynne-wsu added the summary field!

**Comment by michael-wynne-wsu** [comment]
@nick-deer looks good, thanks! I'll make sure it's noted https://github.com/MukurtuCMS/Mukurtu-CMS/issues/192

**Comment by nick-deer** [comment]
Personal collection summary confirmed to be migrating!
