### ISSUE TITLE
/dictionary/[dictionary word]

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#247]
Can broadly start with v3 layout, but there are a few notable differences.
- New location fields (description, map, taxonomy)
- Thumbnail field (new)
- Media assets (new-ish)
- Glossary entry (new, probably does NOT need to be displayed?)
- Source
- Word origin
- Contributor
- Sample sentences (audio) can incorporate embedded text.

![Bonjour-Mukurtu-Demo](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/d803ff21-85f4-4856-a837-a878152956d3)

**Comment by nick-deer** [comment]
@michael-wynne-wsu regarding "Sample sentences (audio) can incorporate embedded text", do you mean that the text field supports full_html format?

**Comment by michael-wynne-wsu** [comment]
@nick-deer it's possible that we ended up choosing NOT to implement this due to complexity, but I couldn't find it referenced (if so, it's probably in meeting notes).

- The sample sentence bundle (/node/add/dictionary_word > entries > additional fields) includes an audio asset field and a text field. That way you can have a text and audio version of the same sentence (or just text or just audio).
- Audio assets (/dashboard/media/add/audio) have a "transcription" metadata field. That's what I meant by embedded text, absolutely the wrong term now that I see it here.
- We at least DISCUSSED using the transcription field to populate the sample sentence field. So if you did fill in the transcription and added an audio sentence, it would pull in the transcription text.

Again, it's entirely possible that we scrapped this on the current iteration in favour of just have the two fields bundled together in the word. And if so, that's quite fine I think.

**Comment by nick-deer** [comment]
@michael-wynne-wsu I pushed a first pass of dictionary display changes-- let me know what you think! I'm still looking into the audio transcription text autofill thing, so that's not reflected in the changes.

**Comment by nick-deer** [comment]
Also @michael-wynne-wsu I found a way to autofill the sample sentence from the audio recording transcription! Upon saving the dictionary word, if the sample sentence field is empty but the recording field is populated, the transcription text gets autofilled. I think it would be better if the text autofilled upon uploading the recording asset, but that seemed too complex to attempt. I pushed up my changes so you can try them if you like!

**Comment by michael-wynne-wsu** [comment]
@nick-deer This is great - I THINK all the fields are coming across as expected. This might be ready to hand off for theming...

**Comment by pjudge** [comment]
Handoff note: I did a first pass at the full display for Dictionary Word content type. It is essentially the same as a digital heritage item currently. Not what we're ultimately going for but it's a start. :) That work is in my most recent PR https://github.com/MukurtuCMS/Mukurtu-CMS/pull/340

**Comment by michael-wynne-wsu** [comment]
Michael needs to review page display and give comments

**Comment by michael-wynne-wsu** [comment]
Closing this because all active items are resolved and it's messy. I created a new issue specifically for theming #586
