### ISSUE TITLE
Browse digital heritage page

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#283]
- [x] /digital-heritage 
- [x] “Apply” button is not responsive 
- [x] Static thumbnails *should* link to items 
- [x] Remove the right-pointing caret ~~Should the arrow accent link to items~~ 
- ~~[ ] Facets shouldn’t force lowercase~~ moved to https://github.com/MukurtuCMS/Mukurtu-CMS/issues/341 
- [x] Should pagination be centered? 
- [x] No, no benefit ~~Should pagination appear at top of list as well?~~ 
- ~~[ ] Map should use side pop-up info window or something equivalent, not the on-map popup~~ moved to https://github.com/MukurtuCMS/Mukurtu-CMS/issues/343
- ~~[ ] Add protocol facet (currently used on /dictionary for reference)~~ moved to https://github.com/MukurtuCMS/Mukurtu-CMS/issues/342

**Comment by michael-wynne-wsu** [comment]
@nick-deer please add protocol browse facet like you did on dictionary browse! (should be on all browse pages probably)

**Comment by pjudge** [comment]
@michael-wynne-wsu I've been digging around and consulting with our designers regarding linking multiple elements inside a single browse teaser. [While it's not an a11y fail, it is not necessarily best practice to have adjacent items linking to the same place. It can become cumbersome for keyboard or screen reader users. ](https://www.w3.org/WAI/WCAG22/Techniques/html/H2)

I see a couple of options moving forward:
1. Group the right-pointing caret with the title and have them be 1 single link. 
2. Remove the right-pointing caret (I don't think it appears in v3?) and just link the title. 
3. Make the entire teaser clickable. I would recommend against this as it requires a bit more JS to make accessible and any time you can skirt using JS is a performance win (well, usually, not always).

**Comment by michael-wynne-wsu** [comment]
@pjudge thanks for this!

I think lets just remove the right-pointing caret entirely, I don't see it adding much benefit.

I *would* like static thumbnails to link as well as the title if possible, or are you saying that's also not good practice?

Audio and video should be rendering players not static thumbnails as well (in case it's not configured like that).

**Comment by pjudge** [comment]
@michael-wynne-wsu Ok, I'll remove the caret and keep the image and title linked. I'll use the [recommendation here](https://accessibleweb.com/question-answer/is-it-compliant-to-have-the-same-link-present-twice-as-both-an-image-and-as-text/) to hide the image from the accessibility tree. It will still be clickable but it won't be announced by SRs and keyboard tabbing will skip the image as well.

**Comment by michael-wynne-wsu** [comment]
That makes perfect sense, thank you!

**Comment by pjudge** [comment]
@michael-wynne-wsu Oops, one more thing! Making the "thumbnails" links works with images, but it not with an audio or video player. We can either keep the representative media un-linked, or use images for all media on browse pages. Thoughts?

**Comment by michael-wynne-wsu** [comment]
@pjudge keep that representative media unlinked please - we've had very positive feedback from users in the past about being to preview or play the media from search results (usually to determine if they want to open the full record)

**Comment by pjudge** [comment]
@michael-wynne-wsu How about both? Link the images, but not the audio and video. (I found a way to do this.)

**Comment by michael-wynne-wsu** [comment]
@pjudge yes that would be my first choice!

**Comment by pjudge** [comment]
>  Facets shouldn’t force lowercase

I don't see anything in the styles causing the lowercase. I can use CSS to force uppercase but it will make every word uppercase, which may or may not be desirable. Otherwise this should maybe be looked into by backend. 

> Should pagination appear at top of list as well?

I would say no to this. Mainly due to the known design pattern being pagination at the bottom. Also as a way to reduce page clutter. If you feel like there are too many items on a single page, we can reduce the number of items per page.

**Comment by michael-wynne-wsu** [comment]
Re: pagination, that sounds good, I'll comment and resolve that.

For facets, here's what I'm seeing. May still be a backend issue and we can flag it as such!

Looking at the category taxonomy as an example. In screenshots the terms show as "Art" and "Default" everywhere except on the browse page where they're "art" and "default".

![Screenshot 2024-05-14 at 1 10 32 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/bc3e4a60-3160-4652-aa1d-d70d5f9e7776)

![Screenshot 2024-05-14 at 1 10 58 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/253241fd-2786-45c0-8975-d05cdfb703e3)

![Screenshot 2024-05-14 at 1 11 24 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/971bcfb4-cfdf-4074-963d-78f2585be211)

![Screenshot 2024-05-14 at 1 11 34 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/cf5396dc-80e2-47a7-896f-692f56ebefaa)

**Comment by pjudge** [comment]
@michael-wynne-wsu I am not 100% sure, but I think the Facets module has some configuration that's causing them to appear lower case. I found this issue https://www.drupal.org/project/facets/issues/3063406 but don't feel entirely comfortable messing with the search config. At this point I would flag as back end, and then, "worst case scenario" is to use CSS to capitalize.

**Comment by michael-wynne-wsu** [comment]
@pjudge absolutely a back end item. I know where those processor settings are in D7 but not D9 yet. I'll log that as a separate back end issue. Thanks!

**Comment by pjudge** [comment]
> Map should use side pop-up info window or something equivalent, not the on-map popup

IHi @michael-wynne-wsu Could you provide a little more information about this? The example site I found on v3 looks like it's also using the on-map popup, unless I'm misunderstanding?

https://aboriginalarchivesitaly.com/browse

**Comment by pjudge** [comment]
> Add protocol facet (currently used on /dictionary for reference)

Also, should this be its own ticket?

**Comment by michael-wynne-wsu** [comment]
@pjudge re: protocol facet.. The facet is already active since it's used on a different browse page, but I'll move that to a new ticket in a bit.

**Comment by michael-wynne-wsu** [comment]
And for the map...
1) Leaflet is still not fully ported over with all of the features we need, but I haven't checked on that for a while. I think that mostly impacted clustering.
2) In the past we've had persistent issues with the map pop up not handling odd-dimension content well, or having media players break the pop up. Again, that's a different map module so may not be an issue, but it was a headache.
3) We saw this sidebar preview come up in testing and that had some appeal over the pop up for consistency if nothing else.

I'm very open to your interpretation and input on this, especially re: accessibility.
The short need is:
- Map view of all mapped content (subject to protocols, search, facets, etc).
- Some way to preview the content from the map (title, thumbnail/media player at a minimum).
- From the preview be able to click through to the content.
- Be aware that we support multiple locations for each piece of content, and that can include any combination of points, lines, rectangles, and polygons. (Not circles, but I think that was also a waiting for leaflet thing).

Additional notes, probably NOT needed for this ticket.
- The same type of map will be present on /browse, /digital-heritage, and /dictionary.
- Outside of browse pages, we want a map option for the homepage.
- V3 did not have a good points clustering system. We were waiting for leaflet to add that.

![Screenshot 2024-05-16 at 8 09 59 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/79a73adf-92d9-4d66-a03b-65daf24801c9)

![Screenshot 2024-05-16 at 8 09 38 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/81dce8e2-a318-41c3-b763-ab572cd21d1a)

**Comment by pjudge** [comment]
@michael-wynne-wsu Testing to see if you get this message. :) I sent an email about meeting today at 10am PT/1pm ET a bit over an hour ago. But maybe it didn't reach you? I received your follow up email asking if we were still meeting. Not sure if it's a gmail issue or something else, so I thought I'd try here via github

**Comment by michael-wynne-wsu** [comment]
@pjudge moved the mapping out of this issue: https://github.com/MukurtuCMS/Mukurtu-CMS/issues/343

**Comment by pjudge** [comment]
Handoff note: Besides the additional map stuff, this issue should be addressed in my PR https://github.com/MukurtuCMS/Mukurtu-CMS/pull/340

**Comment by michael-wynne-wsu** [comment]
Closing this to resolve the PR. New related topic at https://github.com/MukurtuCMS/Mukurtu-CMS/issues/351
