### ISSUE TITLE
Browse all page

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#284]
- /browse 
- Should basically be the same as Browse DH but with the content type facet added.

**Comment by pjudge** [comment]
Handoff note: This work is included in this PR https://github.com/MukurtuCMS/Mukurtu-CMS/pull/340

**Comment by michael-wynne-wsu** [comment]
- [ ] Map view is not loading.
- [ ] Need to confirm default facets.
