### ISSUE TITLE
Admin theme for content management

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#302]
1) Claro should be set as the default admin theme.
2) At /admin/appearance, "Use the administration theme when editing or creating content" should be enabled by default.

**Comment by pjudge** [comment]
Just a note: 1. and 2. are completed in the draft PR i have open currently. 👍

**Comment by michael-wynne-wsu** [comment]
Ah, fantastic! I'll spin the other into it's own issue and sort this one out.
