### ISSUE TITLE
DH full content needs media carousel

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#305]
Currently media display inline - needs a medial carousel like in V3.

**Comment by michael-wynne-wsu** [comment]
Example: https://plateauportal.libraries.wsu.edu/digital-heritage/k%E2%80%99%C3%BAusey%E2%80%99ne-sapo%CB%80saap%C3%B3%CB%80s-womans-saddle-nez-perce

1. When items have enough media assets that the thumbnail carousel becomes scrollable, users can get lost and experience "infinite scroll". Conversely, having to scroll back to the beginning may be annoying.
3. Consider adding a counter (eg: 1/4) and/or displaying filenames/alt text so users can orient themselves (I believe this happens in the v3 zoom image tool).
5. Carousel thumbnails are a fixed size/ratio. They should reflect the proportions of the thumbnail - no cropping.
7. A small number of users prefer NOT to use a carousel. Supporting an inline or alternate display where they can access multiple media assets simultaneously would be a nice option.

**Comment by michael-wynne-wsu** [comment]
@pjudge This was probably a misunderstanding on my part, but I was expecting the carousel would be to select the media and have a more full-size display of the media below. Can you confirm that the screenshot below is showing the whole media assets field as you expected?

The carousel itself is working great though!

![Screenshot 2024-04-26 at 12 30 55 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/9af5ccd2-f7cd-41f3-a749-679a978655d9)

**Comment by pjudge** [comment]
Thanks for reminding me @michael-wynne-wsu -- this was something I wanted to bring up in our next sync. I think that can be done, however I'm wondering about having too much happening on the page at once. Each media asset has a link button that takes the user to the full media for them to experience. That's a click away, but it does improve site performance to not have to have a linked slider. The page gets visually confusing when there's a multipage carousel at the top, and then a page with multiple media assets below. 

I would recommend that if we do keep the larger version of the media asset showing below the carousel, the carousel itself should have much smaller thumbnails. 

I made them larger here as a way to provide users with a decent-sized visual, large enough to allow them to quickly decide if they'd like to click to access the full size version. Just my thoughts -- I can do whichever!

**Comment by michael-wynne-wsu** [comment]
Definitely worth discussing next week!

- Yes, there *can* be way too much going on with the multi-page item carousel, community record tabs, AND multiple media assets. 
- That said, I don't think we will often see much overlap in these features. Certainly good to consider, but I suspect it will be quite a fringe case.
- Historically our users are NOT keen on clicking through to view media in browser, with a strong preference for in-page use. V3 used colorbox to do image zoom, we're going to be adding an in-page PDF viewer hopefully, etc.
- What about something like Splide's thumbnail carousel? that moves the media carousel portion below the focused media asset and away from the MPI/community record navigation when those are present. https://splidejs.com/tutorials/thumbnail-carousel/
- With the above, or even just reducing the existing thumbnail size, the "access media" button would only be needed  by the full/focused media asset, not in the thumbnail view.

**Comment by michael-wynne-wsu** [comment]
@pjudge Only one question on this!

What sets the height of the splide carousel? Height of the tallest slide? 

This leads to excess spacing spacing if the slides have much variation. In *general* this probably isn't much of an issue, except for audio - we see audio + document or audio + portrait image as pretty common combinations.

Best case would be responsive height I think, but no idea about practicality.

![splide 2](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/d0a644f7-2709-4a92-a8af-0ffba5ed5782)


![splide 1](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/6444bf83-deae-4258-b542-8847d8723b71)

**Comment by pjudge** [comment]
@michael-wynne-wsu I've added responsive height handling to the open PR. :)

**Comment by michael-wynne-wsu** [comment]
@pjudge checking that out now!

**Comment by michael-wynne-wsu** [comment]
Absolutely perfect, thank you!

![Screenshot 2024-05-08 at 11 31 02 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/64e5e268-23c4-45f0-9148-b218bd2e7853)

![Screenshot 2024-05-08 at 11 31 09 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/651feea4-9574-4025-859b-62c7d6d99fb1)
