### ISSUE TITLE
Original date display formats

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#308]
On DH items, Original Date only supports YYYY-MM-DD display format.

Please add additional/standard date display formats (eg: January 5, 2024)

Note that this is a custom piece of code since the v3 partial date module was not available. This is a backend issue for @nick-deer and NOT a theming issue for @pjudge

**Comment by nick-deer** [comment]
@michael-wynne-wsu added another display format! Let me know if you have any suggestions, especially with the naming convention of the display formats.

**Comment by michael-wynne-wsu** [comment]
@nick-deer 

For naming, what about "Original Date display - YYYY-MM-DD" and "Original Date display: Month Day, Year". That's a bit easier for me to read. But if there is an established naming convention for these kind of settings, let me know.

Right now they are both working in Bartik, but Mukurtu theme is only displaying "Month Day, Year" regardless of selection. I'm assuming that'll change once approved and you notify Pauline of the update. But yes, I really like having both options available and it's working as expected in bartik!

**Comment by michael-wynne-wsu** [comment]
@nick-deer One tiny note on the date, with "Month Day, Year" format, partial dates include spaces and comma as if the date was complete. But using both formats worked perfectly otherwise.

![Screenshot 2024-05-02 at 1 19 06 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/39b673c2-3945-4986-8762-8fb70e704110)
![Screenshot 2024-05-02 at 1 19 52 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/a31354cc-9107-4395-8a19-8cddc2100d70)

**Comment by michael-wynne-wsu** [comment]
Confirmed complete! @nick-deer
