### ISSUE TITLE
Audio player bug in Chrome

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#317]
Originally from https://github.com/MukurtuCMS/Mukurtu-CMS/issues/239 - in Chrome, the audio player is not displaying.

Nick found the specific bug causing the recording field to look weird, it's been logged: https://www.drupal.org/project/blazy/issues/3424712. 

![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/c0f0a3be-fc5d-498a-9e35-9863876efb30)

Compared to Firefox

![image](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/995363a0-0366-4e0b-a613-32eee478a1b5)

@nick-deer

**Comment by pjudge** [comment]
@michael-wynne-wsu I'm just going through tickets that include the word "Browse" and found this one. Is this ticket still relevant?

**Comment by michael-wynne-wsu** [comment]
@pjudge I think this is no longer relevant. On closer inspection it seemed isolated to the bartik theme... Closing it for now.

![Screenshot 2024-05-17 at 8 15 58 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/d0bac524-f337-4dcb-9e92-88f580de02f7)
