### ISSUE TITLE
External embed media assets - thumbnail required

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#319]
Please make thumbnail a required field for the external embed media type (currently optional).

**Comment by michael-wynne-wsu** [comment]
FYI @nick-deer @pjudge

**Comment by pjudge** [comment]
Handoff note: This should be assigned to back end as again, the fields aren't available in the UI to easily update. :)

**Comment by nick-deer** [comment]
@michael-wynne-wsu Done!

**Comment by michael-wynne-wsu** [comment]
@nick-deer confirmed that it's working, thanks!
