### ISSUE TITLE
Video and audio thumbnails

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#321]
In carousels... (eg: MPI, media assets)
- [x] Video should use a static thumbnail (field already exists and should auto-populate).
- [ ] Audio should use a static thumbnail (either site-default, or unique, see #320).

In other views... (eg: summary/teasers, single media asset)
- [x] Video should use the default player (Youtube, Vimeo, HTML5 for direct upload).
- [x] Audio should use the default player (currently HTML5 - do we want to style one that is consistent across browsers?)

**Comment by michael-wynne-wsu** [comment]
@nick-deer @pjudge

**Comment by pjudge** [comment]
Handoff note: Seeing as how the only remaining part of this that is incomplete has its own ticket (#320 ), this can probably be closed as long as the other points are verified. :)

**Comment by michael-wynne-wsu** [comment]
Agreed, closing.
