### ISSUE TITLE
V3 word lists do not support protocols

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#323]
Needs to be added and included in pre-migration and migration tools.

**Comment by nick-deer** [comment]
Breaking this out into multiple tasks:

- [ ] Add protocols field to word lists in v3 
- [ ] Ensure new protocols field is migrating to v4
- [ ] Ensure pre-migration report catches protocol requirement on word lists

**Comment by nick-deer** [comment]
@michael-wynne-wsu confirmed this is wrapped up too!

**Comment by michael-wynne-wsu** [comment]
@nick-deer fantastic on both! I had some trouble getting my v3 ddev running today but I'll check soon. Feel free to close these.

**Comment by michael-wynne-wsu** [comment]
Tested and confirmed
