### ISSUE TITLE
DH field layout - full view

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#325]
- [x] Review and confirm field display order (@michael-wynne-wsu)
- [x] Consider adding sub-divisions to the sidebar. Even just a more prominent horizontal divide. Eg: core mukurtu fields || additional metadata || rights.
- [x] Broader question: that sidebar is getting extremely full, are there any other display options to improve this?
- ~~If possible, only display node title in sidebar when there is a community record/multi-page item. Not necessary for a standalone DH item. LOW priority at this time.~~ Moved to a standalone issue.
- ~~See also PDF viewer #132~~

**Comment by michael-wynne-wsu** [comment]
@pjudge FYI

**Comment by pjudge** [comment]
Handoff note: I don't think I have anything to add to this, except to point out that there is another ticket that is related to this one that I saw https://github.com/MukurtuCMS/Mukurtu-CMS/issues/334

**Comment by michael-wynne-wsu** [comment]
- Title
   - Local tasks menu
- Left
   - Media assets
   - Summary
   - Description
   - Cultural narrative
   - Traditional knowledge
   - Transcription
   - People
   - Map
   - Location
   - Location description 
   - Related content
- Right
   - Title
   - Communities
   - Cultural protocols
   - Category
   - Keywords
   - Original date
   - Date description
   - Creator
   - Contributor
   - Language
   - Creative commons licenses
   - Local contexts (projects, labels, etc)
   - Source
   - External links
   - Publisher
   - Identifier
   - Subject
   - Type
   - Format
   - Rights and usage
   - Rights statements
   - Citing Indigenous elders and knowledge keepers
   - Citation (computed)

**Comment by pjudge** [comment]
@michael-wynne-wsu I see a "People" field in your lists above, for the left and right sections, however this field is not on the Digital Heritage content type. Should it be?

**Comment by michael-wynne-wsu** [comment]
@pjudge phew! And it should just be in the right section (it's currently in the left section in the build, I would like it moved).

**Comment by pjudge** [comment]
Got it! Thank you. Sorry for the scare!

**Comment by pjudge** [comment]
@michael-wynne-wsu Would you be able to indicate in your list above where the more prominent dividers should be? I have my guesses but would like to be sure. Thanks!

**Comment by michael-wynne-wsu** [comment]
@pjudge I added those in as [break] 
I did move a few fields around in the right section while I was at it.

**Comment by michael-wynne-wsu** [comment]
Note: Map (location) does not need to be visually labelled.

**Comment by michael-wynne-wsu** [comment]
@pjudge I moved the additional notes/items to their own separate issues. I've left this open because of the outstanding indigenous knowledge keepers fieldgroup/empty block thing. Happy to spin that out separately so this can be closed if you prefer.

**Comment by michael-wynne-wsu** [comment]
Never mind, I will do that, I misread my notes. This can be closed when the PR is merged.
