### ISSUE TITLE
Need a default audio thumbnail

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#328]
We need to provide/design a default thumbnail for audio files for use in things like media asset carousels. Without one the carousel operates but there's no "entry" visible for that media asset.

**Comment by pjudge** [comment]
@michael-wynne-wsu Is this something you'd like me to research and come up with some ideas for? Or is there one from WSUL's side that you have in mind?

**Comment by michael-wynne-wsu** [comment]
@pjudge Lets not use your time on this, I will get something together on my end!

**Comment by michael-wynne-wsu** [comment]
@pjudge I had a similar design from another project so updated it with the current colours. Any objections to running these for now?

![audio-thumbnail-blue](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/72bcf4de-228d-4168-9de8-fdb5f4d32e95)

![audio-thumbnail-red](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/38204b5c-0e77-4df1-a2a4-2c33ea7a3111)

**Comment by pjudge** [comment]
![DH_audio](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/15730222/39d0094d-c299-471c-8801-506a6291d236)

Hi @michael-wynne-wsu , those look fine. I just found the above image in the mukurtu profile. Is this also a contender?

**Comment by michael-wynne-wsu** [comment]
@pjudge newer versions for consideration

![audio-thumb-blue](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/41c24a35-89a1-4b6a-a33f-710d5023eb8f)

![audio-thumb-red](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/4dc57e22-af53-401e-b275-4c420c5a8c10)

**Comment by pjudge** [comment]
Handoff note: I wasn't able to set the default image due to the fields not being available in the UI. This should be assigned to a back end dev. :)

**Comment by pjudge** [comment]
Actually looks like this one can be closed in favor of #320 
:)

**Comment by michael-wynne-wsu** [comment]
Agreed!
