### ISSUE TITLE
Browse facets shouldn’t force lowercase

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#341]
Re: pagination, that sounds good, I'll comment and resolve that.

For facets, here's what I'm seeing. May still be a backend issue and we can flag it as such!

Looking at the category taxonomy as an example. In screenshots the terms show as "Art" and "Default" everywhere except on the browse page where they're "art" and "default".

![Screenshot 2024-05-14 at 1 10 32 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/bc3e4a60-3160-4652-aa1d-d70d5f9e7776)

![Screenshot 2024-05-14 at 1 10 58 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/253241fd-2786-45c0-8975-d05cdfb703e3)

![Screenshot 2024-05-14 at 1 11 24 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/971bcfb4-cfdf-4074-963d-78f2585be211)

![Screenshot 2024-05-14 at 1 11 34 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/cf5396dc-80e2-47a7-896f-692f56ebefaa)

From Pauline: I think the Facets module has some configuration that's causing them to appear lower case. I found this issue https://www.drupal.org/project/facets/issues/3063406 but don't feel entirely comfortable messing with the search config. At this point I would flag as back end, and then, "worst case scenario" is to use CSS to capitalize.

**Comment by nick-deer** [comment]
Ah shoot I just saw that category was just an example, do you want all facet titles capitalized, even communities/cultural protocol titles?

**Comment by michael-wynne-wsu** [comment]
@nick-deer I would like all facet titles to reflect the term/entity name as entered. So if I have say keywords for "basketry" and "Nez Perce", they should show up that way.

**Comment by nick-deer** [comment]
Ah I misunderstood haha. I just made a push that actually configures the facets to be their original capitalization

**Comment by michael-wynne-wsu** [comment]
@nick-deer No worries - I tested a few fields and it's looking correct to me now, thank you!

This should be the case on all three browse pages: /browse, /digital-heritage, and /dictionary (and any others we add in the future)

**Comment by nick-deer** [comment]
@michael-wynne-wsu I double checked and it also works for dictionary browse!
