### ISSUE TITLE
Add protocol facet to /browse and /digital-heritage

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#342]
As it says, please add the protocol facet to the two browse pages at /browse and /digital-heritage. It's already present on /dictionary so I believe it should be straightforward.

**Comment by nick-deer** [comment]
@michael-wynne-wsu it's been added!

**Comment by michael-wynne-wsu** [comment]
@nick-deer Great, confirmed that it's present and working, thanks!
