### ISSUE TITLE
Remove dictionary words "additional fields" group

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#345]
"Additional fields" group in create dictionary words > Entries is not needed, all those fields can be part of the entry itself and the grouping removed.

**Comment by pjudge** [comment]
Handoff note: This is addressed in my most recent PR https://github.com/MukurtuCMS/Mukurtu-CMS/pull/340

**Comment by michael-wynne-wsu** [comment]
Complete, thanks!
