### ISSUE TITLE
/digital-heritage

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#351]
At /digital-heritage.

- [x] 3) Remove content type label in preview.
- [x] 4) Protocol facet needs item count.
- [x] 5) Sometimes when switching between views, the results from both views remain on the page. 
- [x] 6) Sometimes the facets cannot be un-checked after applying them.
- [x] 7) Reset button only applies to text search - could/should it be a full page reset?
- [x] 9) Sometimes cannot select multiple items from the same facet.
- [x] 11) In media type facet, external embed is listed as "external_embed".

**Comment by pjudge** [comment]
@michael-wynne-wsu It looks like the /browse page is working correctly, just the digital heritage browse is not. Is that correct?

**Comment by michael-wynne-wsu** [comment]
@pjudge is there a specific issue you're asking about, or just all of the above?
