### ISSUE TITLE
Dictionary Field Changes

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#38]
For context, Michael's ask: https://github.com/WSU-CDSC/mukurtu-cms/discussions/66

Be careful of word entry vs dictionary word.
Word Entries are paragraphs: /admin/structure/paragraphs_type/dictionary_word_entry
Dictionary words are the content type:
/admin/structure/types/manage/dictionary_word

- [x] Add "contributor" field to word entry. Same field as in DH items, taxonomy, multi-value.
- [x] Add "word origin" field to word entry. Single value, plain text (I think).
- [x] Rename "part of speech" to "word type" (word entry).

Do a first pass on sensible entity form display/display for those changes please. Michael called out specifically in the discussion:

> Display language name in dictionary word summary, teaser, etc (dictionary word browse page, elsewhere)

I think that's all the immediately actionable items from that discussion. You did several of them already so I didn't add them to this list. Take a look yourself as well and confirm I didn't miss anything. Thanks!

**Comment by michael-wynne-wsu** [comment]
I think I have word/word entry correct in all instances, but ping me if there's doubt.

**Comment by nick-deer** [comment]
Alright I made the desired changes! Let me know if anything seems amiss.

**Comment by steve-taylor-wsu** [comment]
Looks right at first glance, but could you disable the form display for "Authored on" and "Published" for Dictionary word entry paragraphs? Thanks!

**Comment by nick-deer** [comment]
Done!
