### ISSUE TITLE
Geofield

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#516]
https://www.drupal.org/project/geofield

**Comment by michael-wynne-wsu** [comment]
Unsure why we have it locked to an older version.

**Comment by jonscottwsu** [comment]
Nick updated and tested the geolocation (most recent version 1.59) and we did exploratory testing - all tested functionality appears to be working so far

**Comment by michael-wynne-wsu** [comment]
Awesome - is there anything you need me to look at to confirm?

**Comment by jonscottwsu** [comment]
Geofield was the 3rd module we have worked through the audit process together - I am trying to fully understand (and emulate) Nicks's dev process so we can divvy up the list and make some more headway asap.

This was one of the least complicated module audits so far and we have only done exploratory testing (imported data with geolocation data and created a new digital heritage item) on a local branch so the process of validating the (module) update is still under discussion. I would very much like to discuss with you the details of what "done" looks like and go through the project update as well to make sure you have visibility / status anytime.  Is it possible to discuss (if time allows) in our meeting tomorrow?

Hope all is going well with you and the family - J.Scott

Jonathon Scott
Application Development Team Lead
Washington State University Libraries -- Pullman
509-335-3450 | ***@***.***
________________________________

**Comment by michael-wynne-wsu** [comment]
Yep, we’ll put this on the agenda!

[Washington State University Logo: W, S, U, letters create a cougar head.]
Michael Wynne
Digital Applications Librarian
Center for Digital Scholarship and Curation
Washington State University
Email: ***@***.******@***.***>
The Washington State University Pullman campus is located on the homelands of the Nimíipuu (Nez Perce) Tribe and the Palus people. We acknowledge their presence here since time immemorial and recognize their continuing connection to the land, to the water, and to their ancestors.

From: Jonathon Scott ***@***.***>
Date: Monday, July 8, 2024 at 2:29 PM
To: MukurtuCMS/Mukurtu-CMS ***@***.***>
Cc: Wynne, Michael ***@***.***>, Author ***@***.***>
Subject: Re: [MukurtuCMS/Mukurtu-CMS] Geofield (Issue #516)

[EXTERNAL EMAIL]
Geofield was the 3rd module we have worked through the audit process together - I am trying to fully understand (and emulate) Nicks's dev process so we can divvy up the list and make some more headway asap.

This was one of the least complicated module audits so far and we have only done exploratory testing (imported data with geolocation data and created a new digital heritage item) on a local branch so the process of validating the (module) update is still under discussion. I would very much like to discuss with you the details of what "done" looks like and go through the project update as well to make sure you have visibility / status anytime. Is it possible to discuss (if time allows) in our meeting tomorrow?

Hope all is going well with you and the family - J.Scott

Jonathon Scott
Application Development Team Lead
Washington State University Libraries -- Pullman
509-335-3450 | ***@***.***
________________________________

**Comment by michael-wynne-wsu** [comment]
@jonscottwsu As we talked about, these are the things that I would do exploratory testing to check on Geofield status. And as noted, some of this obviously involves other modules...

1. Migration. Does v3 location data migrate properly?
2. Creation. Within a DH item (and/or any other content types that support mapping), do the following work as expected?
    - Point
    - Polygon
    - Line
    - Rectangle
    - MANY locations
    - Per-location descriptions (click on location to add)
3. View. Do all the locations display properly on the content page AND the browse page? This includes overlapping areas, point clustering, location description tooltips.
4. Edit. Does anything weird happen when the content is edited after being created? Eg: the location data shouldn't disappear!
5. Export. Does the location data come out as expected when run through our export tools?
6. Import. Does the location data work as expected when imported?
    - Updating content
    - Creating new content

**Comment by nick-deer** [comment]
@michael-wynne-wsu I made a test branch with the most current version of Geofield! I could get a Gitpod instance running on it with no issues. Let me know if it works for you:

https://github.com/MukurtuCMS/Mukurtu-CMS/tree/test-updated-geofield-module

**Comment by michael-wynne-wsu** [comment]
@nick-deer it all seems to be working as well as before, so I think you can include that in core and mark this module as up to date!
