### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#520]
https://www.drupal.org/project/message

**Comment by nick-deer** [comment]
@michael-wynne-wsu @jonscottwsu tested the latest Message module, it looks okay on my end--rigged up a test branch of it here for you guys to check out: https://github.com/MukurtuCMS/Mukurtu-CMS/tree/test-current-message-module

**Comment by jonscottwsu** [comment]
right on! thank you for digging into this module Nick

**Comment by michael-wynne-wsu** [comment]
@nick-deer I don't know that I've explicitly thought about this module - can you quickly let me know what it does in our use case?

**Comment by nick-deer** [comment]
Yeah @michael-wynne-wsu the message module basically just deals with the system messages, like the messages at the top of the page when submit happens (e.g. "Item saved" and "User created", that sort of thing).

**Comment by michael-wynne-wsu** [comment]
@nick-deer Gotcha, thank you! It seems to be working fine for me, I think this can be merged anytime.
