### ISSUE TITLE
V3 dictionary add thumbnail field

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#562]
Add thumbnail field (alongside media assets field) in v3 so that users can move images into thumbnail field from additional media assets during pre-migration activities.

**Comment by nick-deer** [comment]
@michael-wynne-wsu I added it and it's showing up on my end!

**Comment by michael-wynne-wsu** [comment]
@nick-deer fantastic! I don't have an easy way to build a v3 site to test, but I'm happy for you to mark this complete without me confirming if you're okay with that.
