### ISSUE TITLE
Pronunciation field not migrating

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#573]
Reported by @nick-deer 

Pronunciation field date is not currently being migrated from v3.

**Comment by nick-deer** [comment]
@michael-wynne-wsu fixed it! It's working for me, let me know when you verify it on your end

**Comment by michael-wynne-wsu** [comment]
@nick-deer I don't have an easy way to set up and test V3>v4 migration right now. We can check with @brian-wsu in the dev meeting, or I'm fine trusting your testing here
