### ISSUE TITLE
Local Contexts project pages description

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#583]
/dashboard/local-contexts/projects/directory

Directory description should be HTML not plain text.

Same for community and protocol levels.

**Comment by nick-deer** [comment]
I changed it over! I've got my changes on a separate branch: https://github.com/MukurtuCMS/Mukurtu-CMS/tree/583-local-contexts-project-pages

**Comment by michael-wynne-wsu** [comment]
Noted over there, but confirming that's what I wanted, thanks!
