### ISSUE TITLE
Computed citation field

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#584]
I know Steve worked on a computed citation field #188 but I can't tell if this has made it anywhere into the current front end at all.

**Comment by michael-wynne-wsu** [comment]
@nick-deer If you can find this, just let me know if it's present or not. I know it's not in any theming, but not sure if there's *any* front end config etc.

**Comment by nick-deer** [comment]
@michael-wynne-wsu we have computed citation field template settings at admin/config/mukurtu/settings iirc, and the code for it is in the mukurtu_core module. Let me know if I can point you to anything more specific!

**Comment by michael-wynne-wsu** [comment]
@nick-deer ah yes THANK YOU. Got it, and it's already in display.
