### ISSUE TITLE
Dictionary word layout full view

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#586]
NOTE: there is a repeatable paragraph "word entry", and only the first is currently displaying.

Top
- Page title/dictionary word Term field
- Local task menu

Left
- Word entry 1 (this whole block repeats)
   - Alternate spelling
   - Translation
   - Recording
   - Definition
   - Sample sentences (mix of text and audio)
   - Word type
   - Pronunciation
   - Source
   - Word origin
   - Contributor
- Word entry 2 (etc)

Visual separator

- Media assets (not really sure about this placement)
- Map (does not need the "Location" label)
- Location
- Location description
- Citation (may not be added yet)

Right
- Community (can community/protocols be combined?)
- Cultual protocols
- Language
- Glossary entry (?)
- Keywords
- Thumbnail (maybe?)
- Word lists 
- Related content
- Local Contexts/TK Labels (may not be added yet)

V3 screenshot attached for reference 

![Image](https://github.com/user-attachments/assets/61d170a0-fad6-4997-87d8-c71fd8f582c0)

**Comment by michael-wynne-wsu** [comment]
Can visually hide map (location) label (and same on DH view)

**Comment by michael-wynne-wsu** [comment]
Back end - we should test splitting out the "core" entry from word entries.

**Comment by pjudge** [comment]
@michael-wynne-wsu  For the sidebar (right column) on this display, would the separations we're trying to do for DH nodes need to be added here too? Or can all the sidebar fields appear in the same styled block?

**Comment by michael-wynne-wsu** [comment]
### Top
- Page title Term (from "Mukurtu essentials" tab on create form)
- Local task menu

### Left 
- "Base word" (all from "Mukurtu essentials" tab on create form
   - Alternate spelling
   - Translation
   - Recording
   - Definition
   - Sample sentences (mix of text and audio)
   - Word type
   - Pronunciation (formatted text)
   - Source
   - Word origin
   - Contributor
#### Some kind of visual separation between entries
- Repeatable word entry paragraphs (from "word entries" tab on create form)
   - Term
   - Alternate spelling
   - Translation
   - Recording
   - Definition
   - Sample sentences (mix of text and audio)
   - Word type
   - Pronunciation (formatted text)
   - Source
   - Word origin
   - Contributor

#### Visual separator
(from "Additional fields" tab on create form)
- Media assets (not really sure about this placement)
- Map (does not need the "Location" label)
- Location
- Location description
- Citation (may not be added yet)

### Right (most from "Mukurtu essentials" tab on create form)
- Community (can community/protocols be combined?) 
- Cultual protocols 
- Language
- Glossary entry (?)
- Keywords 
- Thumbnail (maybe?) 
- Word lists (referenced field - words will be added into word lists from the word list side but should be displayed here)
- Related content (from "Relations" tab on create form)
- Local Contexts/TK Labels (may not be added yet)

**Comment by pjudge** [comment]
note to self: check out dictionary word teasers on Browse

**Comment by michael-wynne-wsu** [comment]
Final notes - and if any of these are just a local/Michael issue, let me know.
- [ ] Remove thumbnail in sidebar 
- [ ] Word entry missing main term/red label 
- [ ] Try alternate display of recording contributor
- [ ] Add related content to display
- [ ] Some fields missing dividers
- [ ] Previous /dictionary (browse) page no longer displaying properly

@pjudge
