### ISSUE TITLE
Can't upload media assets to tugboat builds

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#640]
Unsure exactly when it started, but at least present in https://github.com/MukurtuCMS/Mukurtu-CMS/tree/d1d55885c1d6246870699082e94fb045ac76a166 and newer

![Screenshot 2024-11-22 at 11 45 06 AM](https://github.com/user-attachments/assets/17f1c560-f364-4dcd-92f9-0e440ca43259)

![Details-Mukurtu-CMS-11-22-2024_11_45_AM](https://github.com/user-attachments/assets/6e8ab9cc-f375-4772-969f-8f4897758dbc)

**Comment by quicksketch** [comment]
PR filed at https://github.com/MukurtuCMS/Mukurtu-CMS/pull/642 that should fix private file configuration on Tugboat.

Note we'll need to rebuild the base preview after this is merged to apply the change to other sandboxes.

**Comment by michael-wynne-wsu** [comment]
Merged and rebuilding now
