### ISSUE TITLE
Add BC Labels and Notices

### ISSUE THREAD

**Issue by steve-taylor-wsu** [MukurtuCMS/Mukurtu-CMS#80]
We need to add the local contexts "BC Labels" and "Notices" to the new project and label fields.

The local contexts hub API documentation is here: https://localcontexts.org/support/api-guide/

Don't trust their examples, some are out of date. Here are some examples of live test server projects with:

A notice: https://anth-ja77-lc-dev-42d5.uc.r.appspot.com/api/v1/projects/c6e66952-6d5c-42d4-9642-65532bf3c1f1
BC Labels: https://anth-ja77-lc-dev-42d5.uc.r.appspot.com/api/v1/projects/a59ee8f5-5feb-41bf-b255-788909c1dfff

## User Experience
Right now, the "Local Contexts Projects" field currently shows only TK Labels. It should show all labels (TK & BC) and all notices. Users should continue to select only projects for this field.

The "Local Contexts Labels" field lets users select individual labels right now. Ideally, Michael would like BC labels AND notices to be added to this selector, so the user can individually select from all "things" in a project. BC Labels should be easy, I believe their data format is 1:1 with TK Labels. Notices could be tougher. Labels are stored as project_id:label_id in the field, but notices don't have IDs. Notices aren't customizable so I think we can use project_id:notice_type, but I'm not sure if I've painted us into a corner with the code or not.

I'd recommend you understand the entire mukurtu_local_contexts module well before you jump into code. One thing I'll point is out that `LocalContextsProject.php` is the only place that handles fetching from the hub. It should remain this way. LocalContextsProject populates our local "cache" tables defined in the schema in `mukurtu_local_contexts.install`. If you need to pull info about BC labels or notices, it should come from our tables (just like TK labels right now).

You'll probably have questions but really try to understand the module. My LocalContexts* classes are slightly different but everything else is very common Drupal development, worth knowing.

**Comment by steve-taylor-wsu** [comment]
@nick-deer: With initial testing this seems to work well for the "Local Contexts Labels and Notices" field but the "Local Contexts Projects" doesn't display the BC labels or notices for me. That field should always display all labels/notices for the selected project(s).

Also, the logs are full of warnings, can you please change it so it doesn't produce those. Here's an example (this is one of several keys):

```
Warning: Undefined array key "svg_url" in Drupal\mukurtu_local_contexts\LocalContextsSupportedProjectManager->getUserNotices() (line 249 of /var/www/html/web/profiles/contrib/mukurtu-cms/modules/mukurtu_local_contexts/src/LocalContextsSupportedProjectManager.php)
```

**Comment by nick-deer** [comment]
@steve-taylor-wsu I have Local Contexts Projects displaying BC labels and notices now, and I've also fixed the warnings in the logs!
