### ISSUE TITLE
Original date field validation

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#84]
Original date should either provide helper text on accepted input or, preferably, allow input for YYYY, MM, and DD via dropdown instead of text fields.

**Comment by steve-taylor-wsu** [comment]
@nick-deer I think @michael-wynne-wsu wants this exactly like v3 which uses select widgets for both month and day (rather than number).

**Comment by nick-deer** [comment]
Alright I made the change!

**Comment by steve-taylor-wsu** [comment]
@michael-wynne-wsu Do you want month names like in v3? Currently @nick-deer has numbers. This is one of those situations where I don't know what was an intentional choice vs a by-product of the contrib module providing the widget in v3.

**Comment by michael-wynne-wsu** [comment]
@steve-taylor-wsu not an intentional choice in v3, as far as I remember.

My preference would be a hybrid version with both number and name, like _1-Jan_
Month name is my second choice if the above has issues
