### ISSUE TITLE
Video players

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#85]
Need to add video players (tested with Vimeo) to all places a video would display - media asset, thumbnail, HTML embed, etc. Currently only displays a static thumbnail.

**Comment by michael-wynne-wsu** [comment]
I suspect this doesn't really help, but it's rendering fine on a gitpod build I made this morning.

![Screenshot 2024-04-26 at 9 01 33 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/8ad94e1d-fe28-4ef7-8a3e-e2d9cf2d0eb6)

**Comment by pjudge** [comment]
Thanks! I figured out the issue. I'm working on one more thing and should have this PR open for review in a bit.

**Comment by michael-wynne-wsu** [comment]
@pjudge confirmed that this is complete!
