### ISSUE TITLE
Map not displaying on map view - browse pages

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#89]
No map is displaying when a browse is set to map view. Did confirm that there is location data in some DH items for testing.

**Comment by steve-taylor-wsu** [comment]
Confirmed site specific, the map scripts are getting filtered out on the new dev server. We'll figure out if it's the way we package them or something specific to the dev server.

**Comment by steve-taylor-wsu** [comment]
I never got around to checking the dev server issue, but I'd recommend waiting to until #185 is done/decided.

**Comment by pjudge** [comment]
@michael-wynne-wsu Is this still relevant?

**Comment by michael-wynne-wsu** [comment]
@pjudge No, it seems to be resolved and was probably environment specific. Thanks for flagging that, closing the issue.
