### ISSUE TITLE
Error when using non-latin characters in dictionary word title

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#91]
Site generates an unexpected error when trying to include (some?) non-latin characters in the term/title field of a dictionary word.

Happens with à and α - haven't tested other characters.

No issue including those characters in DH titles, taxonomy terms.
![Details-Mukurtu-CMS2](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/7e5729f0-53e9-492b-8af1-4ab185a5085a)
![Details-Mukurtu-CMS](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/9392a004-0acb-4598-9f3b-64aafc0a9d1a)
![Screenshot 2023-08-23 at 11 19 54 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/ccaa8b2c-b246-4d34-a3b2-5b56b1707ae5)
![Screenshot 2023-08-23 at 11 20 04 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/fb4cd801-a514-4081-92e9-3913f89b2705)

**Comment by steve-taylor-wsu** [comment]
@nick-deer I'd recommend starting by looking at DictionaryWord's presave method. Just a guess but I suspect we need to use some PHP multibyte string functions rather than accessing the raw array.

**Comment by michael-wynne-wsu** [comment]
Looks good to me in a fresh gitpod build, thanks!

[Washington State University Logo: W, S, U, letters create a cougar head.]
Michael Wynne
Digital Applications Librarian
Center for Digital Scholarship and Curation
Washington State University
Email: ***@***.******@***.***>
The Washington State University Pullman campus is located on the homelands of the Nimíipuu (Nez Perce) Tribe and the Palus people. We acknowledge their presence here since time immemorial and recognize their continuing connection to the land, to the water, and to their ancestors.

From: Nick Deer ***@***.***>
Date: Thursday, August 31, 2023 at 1:18 PM
To: MukurtuCMS/Mukurtu-CMS ***@***.***>
Cc: Wynne, Michael ***@***.***>, Author ***@***.***>
Subject: Re: [MukurtuCMS/Mukurtu-CMS] Error when using non-latin characters in dictionary word title (Issue #91)

[EXTERNAL EMAIL]

Closed #91<https://urldefense.com/v3/__https://github.com/MukurtuCMS/Mukurtu-CMS/issues/91__;!!JmPEgBY0HMszNaDT!oNlJpdDZpY6V9pd0Ifvf2Ktir40GCD8TyNGIu3X6DGtSCpHo3Hi9Ht0cumbYvrThbXL-FAkVBo6gnniHUXdnG3vFqVPd$> as completed.
